name: eduwise
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # ğŸš€ State Management & Navigation
  get: ^4.6.6
  provider: ^6.1.5+1

  # ğŸŒ Networking
  dio: ^5.4.0
  connectivity_plus: ^6.0.2

  # ğŸ”’ Authentication & Security
  google_sign_in: ^7.1.1
  flutter_secure_storage: ^9.0.0


  # ğŸ“¦ Local Storage & Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # ğŸ–¼ UI & UX
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.9
  lottie: ^3.1.2
  flutter_rating_bar: ^4.0.1


  # ğŸ“ Maps & Location
  google_maps_flutter: ^2.7.0
  geolocator: ^14.0.2

  # ğŸ“‘ File & Reports
  file_picker: ^10.3.2
  pdf: ^3.11.0
  open_filex: ^4.5.0

  # ğŸ›  Utilities
  logger: ^2.3.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/logo-red.png